FROM nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1
ENV SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True

RUN apt-get update --fix-missing \ 
    && apt-get install -y --fix-missing \
    python3.9 \
    python3-pip \
    build-essential \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgtk-3-dev \
    python3-tk \
    xvfb \
    git \
    curl \
    openssh-server \
    && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python

RUN pip install --upgrade pip setuptools wheel
RUN pip install --no-cache-dir --upgrade importlib-metadata
RUN pip install --no-cache-dir \
    torch==1.13.0+cu116 \
    torchvision==0.14.0+cu116 \
    torchaudio==0.13.0+cu116 \
    --extra-index-url https://download.pytorch.org/whl/cu116

RUN pip install --no-cache-dir \
    torchtext==0.14.0 \
    scipy==1.8.1 \
    tqdm==4.64.1 \
    matplotlib==3.3.1 \
    kornia==0.6.9 \
    simple-3dviz \
    transformers==4.25.1 \
    pyvista==0.43.3 \
    trimesh==3.12.7 \
    wandb==0.18.0 \
    openai-clip==1.0.1 \
    clean-fid \
    pillow \
    num2words \
    nltk \
    einops_exts \
    seaborn \
    gdown

RUN pip install --no-cache-dir open3d

RUN pip install --no-cache-dir \
    vessl \
    jupyterlab \
    jupyterlab-git \
    ipywidgets

# echo 'set -o emacs' >> ~/.bashrc
# echo 'bind "\C-f": forward-word' >> ~/.bashrc
# echo 'bind "\C-b": backward-word' >> ~/.bashrc
# source ~/.bashrc